'use strict'

require('./tools/buildFilter.test')
require('./tools/buildQuery.test')
require('./tools/getTimeString.test')
require('./tools/normalizeUrl.test')
require('./tools/parseQueryString.test')
require('./tools/parseTimeString.test')
require('./getAuthHeader.test')
require('./matchers.test')
require('./parseUrl.test')
require('./buildUrl.test')
require('./index.test')
require('./fetchUrl.test')
require('./fetchOptions.test')
require('./DELETE.test')
require('./errorsHandle.test')
require('./getResponseError.test')
require('./events.test')
